# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3'
services:
  db:
    image: jainnish94/hygieia-mongodb-centos
    ports:
      - "27017:27017"
    volumes:
      - "db-data:/data/db"

  db-setup:
    image: jainnish94/hygieia-mongodb-setup
    depends_on:
      - db

  api:
    image: jainnish94/hygieia-api
    depends_on:
      - db-setup
    ports:
      - "8080:8080"

  api-audit:
    image: jainnish94/hygieia-api-audit
    depends_on:
      - db-setup
    ports:
      - "8081:8080"

  ui:
    image: jainnish94/hygieia-ui
    depends_on:
      - api
    ports:
      - "3000:80"

  appdynamics-collector:
    image: jainnish94/hygieia-appdynamics-collector
    depends_on:
      - db-setup

  artifactory-artifact-collector:
    image: jainnish94/hygieia-artifactory-artifact-collector
    depends_on:
      - db-setup

  bamboo-build-collector:
    image: jainnish94/hygieia-bamboo-build-collector
    depends_on:
      - db-setup

  bitbucket-collector:
    image: jainnish94/hygieia-bitbucket-scm-collector
    depends_on:
      - db-setup

  chat-ops-collector:
    image: jainnish94/hygieia-chat-ops-collector
    depends_on:
      - db-setup

  hpsm-cmdb-collector:
    image: jainnish94/hygieia-hpsm-cmdb-collector
    depends_on:
      - db-setup

  github-collector:
    image: jainnish94/hygieia-github-scm-collector
    depends_on:
      - db-setup

  github-graphql-collector:
    image: jainnish94/hygieia-github-graphql-scm-collector
    depends_on:
      - db-setup

  gitlab-feature-collector:
    image: jainnish94/hygieia-gitlab-feature-collector
    depends_on:
      - db-setup

  gitlab-scm-collector:
    image: jainnish94/hygieia-gitlab-scm-collector
    depends_on:
      - db-setup

  jenkins-build-collector:
    image: jainnish94/hygieia-jenkins-build-collector
    depends_on:
      - db-setup

  jenkins-codequality-collector:
    image: jainnish94/hygieia-jenkins-codequality-collector
    depends_on:
      - db-setup

  jenkins-cucumber-test-collector:
    image: jainnish94/hygieia-jenkins-cucumber-test-collector
    depends_on:
      - db-setup

  jira-collector:
    image: jainnish94/hygieia-jira-feature-collector
    depends_on:
      - db-setup

  nexus-iq-collector:
    image: jainnish94/hygieia-nexus-iq-collector
    depends_on:
      - db-setup

  sonar-codequality-collector:
    image: jainnish94/hygieia-sonar-codequality-collector
    depends_on:
      - db-setup

  # subversion-collector:
  #
  #     - db-setup

  udeploy-collector:
    image: jainnish94/hygieia-udeploy-collector
    depends_on:
      - db-setup

  versionone-collector:
    image: jainnish94/hygieia-versionone-collector
    depends_on:
      - db-setup

  xldeploy-collector:
    image: jainnish94/hygieia-xldeploy-collector
    depends_on:
      - db-setup

  score-collector:
    image: jainnish94/hygieia-score-collector
    depends_on:
      - db-setup

volumes:
  db-data:
  certs:
